# Generated by Django 5.1.2 on 2024-11-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='intereses',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='orientacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferencia',
            field=models.CharField(blank=True, choices=[('Amistad', 'Amistad'), ('Estudio', 'Estudio'), ('Relación', 'Relación')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingeniería Civil', 'Ingeniería Civil'), ('Derecho', 'Derecho'), ('Medicina', 'Medicina')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, choices=[('Santiago', 'Santiago'), ('Viña del Mar', 'Viña del Mar'), ('Concepción', 'Concepción')], max_length=50, null=True),
        ),
    ]
