# Generated by Django 5.1.2 on 2024-11-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_bio_remove_usuario_intereses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ver_genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Todos', 'Todos')], default='Todos', max_length=50, null=True),
        ),
    ]
