# Generated by Django 5.1.2 on 2024-11-04 01:48

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_ver_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ver_genero',
            new_name='genero_preferido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='carreras_preferidas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ingeniería Civil', 'Ingeniería Civil'), ('I. Civil informatica', 'I. Civil informatica'), ('I. Civil Mecánica', 'I. Civil Mecánica')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sedes_preferidas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Casa central', 'Casa central'), ('Viña del Mar', 'Viña del Mar'), ('Concepción', 'Concepción'), ('Vitacura', 'Vitacura'), ('San joaquin', 'San joaquin')], max_length=57, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingeniería Civil', 'Ingeniería Civil'), ('I. Civil informatica', 'I. Civil informatica'), ('I. Civil Mecánica', 'I. Civil Mecánica')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, choices=[('Casa central', 'Casa central'), ('Viña del Mar', 'Viña del Mar'), ('Concepción', 'Concepción'), ('Vitacura', 'Vitacura'), ('San joaquin', 'San joaquin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10º Semestre')], null=True),
        ),
    ]
